version: "3"
services:
  api:
    container_name: "api"
    image: dixennaxos/pa-4al2-gr5:api-${ENV}-latest
    ports:
      - '7590:7590'
    restart: "always"
    tty: true
    volumes:
      - "./api/.env:/.env"
      - "./api/logs:/logs"
  gamemanager:
    container_name: "gamemanager"
    image: dixennaxos/pa-4al2-gr5:game-manager-${ENV}-latest
    ports:
      - '7589:7589'
    restart: "always"
    tty: true
    volumes:
      - "./game-manager/.env:/.env"
      - "./game-manager/logs:/logs"
  dockermanager:
    container_name: "dockermanager"
    image: dixennaxos/pa-4al2-gr5:docker-manager-${ENV}-latest
    ports:
      - '7588:7588'
    restart: "always"
    tty: true
    volumes:
      - "./docker-manager/env.py:/code/env.py"
      - "./docker-manager/dockerfiles:/code/dockerfiles"
      - "./game-manager/resources/games:/code/dockerfiles/games"
      - "/var/run/docker.sock:/var/run/docker.sock"
  front:
    container_name: "front"
    image: dixennaxos/pa-4al2-gr5:front-${ENV}-latest
    ports:
      - '3000:3000'
    restart: "always"
    tty: true
    volumes:
      - "./web/coding-games/.env:/.env"
  nginx:
    container_name: "nginx"
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ../arlo-4a-pa-conf/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - api
      - gamemanager
      - front
  certbot:
    container_name: "certbot"
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
