pub mod response_enum;
pub mod message_response;
pub mod lobby_member_response;
pub mod lobby_response;
pub mod error_response;
pub mod invite_response;
pub mod game_response;
pub mod friend_list_response;
pub mod user_response;