pub mod request;
pub mod response;
pub mod init_ranking;
pub mod update_ranking;
pub mod delete_by_user;
pub mod delete_by_game;
pub mod get_ranking_by_game;
pub mod get_ranking_by_friend;
pub mod get_ranking_by_user;
