name: API

on:
  push:
    branches: [ "main", "test", "dev" ]
    paths: 
      - 'api/Cargo.toml'

env:
  CARGO_TERM_COLOR: always
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cd api
        cargo build --verbose
    - name: Run tests
      run: |
        cargo test --verbose
      
  build:
    needs: tests
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with: 
          context: ./api
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{DOCKERHUB_PROJECT_NAME}}:api-${{env.BRANCH_NAME}}-latest
    
  redeploy:
    needs: build
    name: Redeploy
    runs-on: ubuntu-latest
    steps:
      - name: Connect and exec
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets[format('SERVER_HOSTNAME_{0}', env.BRANCH_NAME)] }}
          username: ${{ secrets[format('SERVER_USERNAME_{0}', env.BRANCH_NAME)] }}
          key: ${{ secrets[format('SERVER_KEY_{0}', env.BRANCH_NAME)] }}
          script: |
            cd arlo-4a-pa/
            git pull
            docker compose pull
            docker compose up -d
            docker image prune -f
