name: FRONT

on:
  push:
    branches: [ "main", "test", "dev" ]
    paths:
      - 'web/coding-games/package.json'

env:
  CARGO_TERM_COLOR: always
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./web/coding-games
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_PROJECT_NAME}}:front-${{env.BRANCH_NAME}}-latest

  redeploy:
    needs: build
    name: Redeploy
    runs-on: ubuntu-latest
    steps:
      - name: Connect and exec
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets[format('SERVER_HOSTNAME_{0}', env.BRANCH_NAME)] }}
          username: ${{ secrets[format('SERVER_USERNAME_{0}', env.BRANCH_NAME)] }}
          key: ${{ secrets[format('SERVER_KEY_{0}', env.BRANCH_NAME)] }}
          script: |
            cd arlo-4a-pa/
            git pull
            docker compose pull
            docker compose up -d
            docker image prune -f
