name: GAME MANAGER

on:
  push:
    branches: [ "main", "test", "dev" ]
    paths:
      - 'game-manager/Cargo.toml'

env:
  CARGO_TERM_COLOR: always
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd game-manager
          cargo build --verbose
      - name: Run tests
        run: |
          cd game-manager
          cargo test --verbose

  build:
    needs: tests
    name: Build docker image
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Dockerhub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./game-manager
          platforms: linux/arm64
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_PROJECT_NAME}}:api-game-${{env.BRANCH_NAME}}-latest

  redeploy:
    needs: build
    name: Redeploy
    runs-on: self-hosted
    steps:
      - name: Connect and exec
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets[format('SERVER_HOSTNAME_{0}', env.BRANCH_NAME)] }}
          username: ${{ secrets[format('SERVER_USERNAME_{0}', env.BRANCH_NAME)] }}
          key: ${{ secrets[format('SERVER_KEY_{0}', env.BRANCH_NAME)] }}
          script: |
            cd arlo-4a-pa/
            git pull
            docker compose pull
            docker compose up -d
            docker image prune -f
